<ips:template parameters="$player" />
{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack('module__gamepanel_overview'), \IPS\Member::loggedIn()->language()->addToStack('module__gamepanel_overview_blurb')"}
<div class='ipsColumns ipsColumns_collapsePhone'>
	<div class='ipsColumn ipsColumn_fluid'>
		<ul class='ipsDataList'>
            <li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
                    <h4 class='ipsDataItem_title'><strong>{lang="gp_ign"}</strong></h4><br>
                    {$player->ign}
                </div>
            </li>
            <li class='ipsDataItem'>
                <div class='ipsDataItem_main'>
                    <h4 class='ipsDataItem_title'><strong>{lang="gp_uuid"}</strong></h4><br>
                    {$player->uuid}
                </div>
            </li>
            <li class='ipsDataItem'>
                <div class='ipsDataItem_main'>
                    <h4 class='ipsDataItem_title'><strong>{lang="gp_servers_access"}</strong></h4><br>
                    <span class="ipsBadge ipsBadge_negative ipsBadge_large">
                    Main <i class="fa fa-gavel"></i>
                    </span>
                    <span class="ipsBadge ipsBadge_positive ipsBadge_large">
                    Test <i class="fa fa-check"></i>
                    </span>
                    <span class="ipsBadge ipsBadge_positive ipsBadge_large">
                    Games <i class="fa fa-check"></i>
                    </span>
                    <span class="ipsBadge ipsBadge_neutral ipsBadge_large">
                    Build <i class="fa fa-remove"></i>
                    </span>
                    <span class="ipsBadge ipsBadge_neutral ipsBadge_large">
                    Dark Portal <i class="fa fa-remove"></i>
                    </span>
                </div>
            </li>
        </ul>
    </div>
</div>